version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0  # Use CircleCI's OpenJDK 17 image
    steps:
      - checkout  # Check out source code
      # - run:
      #     name: Install dependencies
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get install -y --no-install-recommends gradle
      - run:
          name: Run tests
          command: gradle -p config/config-server clean build test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
